server:
  port: 7001

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    register-with-eureka: false    #false:不作为一个客户端注册到注册中心
    fetch-registry: false          #false表示自己端就是注册中心，我的职责就是维护实例，并不需要去检索服务
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false        #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 10000   #清理间隔（单位毫秒，默认是60*1000）10秒将客户端剔除的服务在服务注册列表中剔除



